[project]
name = "trading"
version = "0.1.0"
description = "librarie use for my python API"
readme = "README.md"
authors = [
    { name = "Ricardo Cancar", email = "ricardocancar@gmail.com" }
]
license = { text = "MIT License" }
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.dependencies]
numpy = ">2.1.0"
pandas = ">2.2.0"
yfinance = ">0.2.0"
pytest = ">8.3.0"
streamlit = ">1.38.0"
fastapi = ">0.115.0"
pydantic-settings = ">=2.5.0"
sqlmodel = ">=0.0.8"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
