name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop

env:
  PYTHON_VERSION: "3.11"
  COVERAGE_THRESHOLD: ${{ github.ref == 'refs/heads/main' && 80 || 70 }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install linting tools
        run: |
          pip install flake8
      - name: Run flake8
        run: |
          flake8 src/

  test:
    runs-on: ubuntu-latest
    needs: lint  # Ensure linting is successful before tests run
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest --cov=src --cov-report=term --cov-fail-under=${{ env.COVERAGE_THRESHOLD }}
